version: '3.8'
services:
  grafana:
    image: grafana/grafana
    ports:
      - ${service_grafana_host_port}:${service_grafana_container_port}
    hostname: paperlesscv_server_grafana
    container_name: paperlesscv_server_grafana
    depends_on:
      - prometheus
  redis:
    image: redis:latest
    ports:
      - ${service_redis_host_port}:${service_redis_container_port}
    hostname: paperlesscv_server_redis
    container_name: paperlesscv_server_redis
  sqlServer:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: YourStrong@Passw0rd
    ports:
      - '5510:1433'
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./docker/volumes/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
networks:
  backend:
    driver: bridge
